# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.kr.co.lguplus.engine.model.v1 import stt_pb2 as kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kr/co/lguplus/engine/service/v1/stt_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SttServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStream = channel.stream_stream(
                '/kr.co.lguplus.engine.service.v1.SttService/GetStream',
                request_serializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamRequest.SerializeToString,
                response_deserializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamReply.FromString,
                _registered_method=True)
        self.LMUpdate = channel.unary_unary(
                '/kr.co.lguplus.engine.service.v1.SttService/LMUpdate',
                request_serializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.LMUpdateRequest.SerializeToString,
                response_deserializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.LMUpdateReply.FromString,
                _registered_method=True)
        self.InterLMUpdate = channel.unary_unary(
                '/kr.co.lguplus.engine.service.v1.SttService/InterLMUpdate',
                request_serializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.InterLMUpdateRequest.SerializeToString,
                response_deserializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.InterLMUpdateReply.FromString,
                _registered_method=True)


class SttServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LMUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InterLMUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SttServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamRequest.FromString,
                    response_serializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamReply.SerializeToString,
            ),
            'LMUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.LMUpdate,
                    request_deserializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.LMUpdateRequest.FromString,
                    response_serializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.LMUpdateReply.SerializeToString,
            ),
            'InterLMUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.InterLMUpdate,
                    request_deserializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.InterLMUpdateRequest.FromString,
                    response_serializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.InterLMUpdateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kr.co.lguplus.engine.service.v1.SttService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kr.co.lguplus.engine.service.v1.SttService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SttService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kr.co.lguplus.engine.service.v1.SttService/GetStream',
            kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamRequest.SerializeToString,
            kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LMUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kr.co.lguplus.engine.service.v1.SttService/LMUpdate',
            kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.LMUpdateRequest.SerializeToString,
            kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.LMUpdateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InterLMUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kr.co.lguplus.engine.service.v1.SttService/InterLMUpdate',
            kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.InterLMUpdateRequest.SerializeToString,
            kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.InterLMUpdateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
