# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kr/co/lguplus/engine/service/v1/stt.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.kr.co.lguplus.engine.model.v1 import stt_pb2 as kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)kr/co/lguplus/engine/service/v1/stt.proto\x12\x1fkr.co.lguplus.engine.service.v1\x1a\'kr/co/lguplus/engine/model/v1/stt.proto2\xda\x02\n\nSttService\x12i\n\tGetStream\x12,.kr.co.lguplus.engine.model.v1.StreamRequest\x1a*.kr.co.lguplus.engine.model.v1.StreamReply(\x01\x30\x01\x12h\n\x08LMUpdate\x12..kr.co.lguplus.engine.model.v1.LMUpdateRequest\x1a,.kr.co.lguplus.engine.model.v1.LMUpdateReply\x12w\n\rInterLMUpdate\x12\x33.kr.co.lguplus.engine.model.v1.InterLMUpdateRequest\x1a\x31.kr.co.lguplus.engine.model.v1.InterLMUpdateReplyB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kr.co.lguplus.engine.service.v1.stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_STTSERVICE']._serialized_start=120
  _globals['_STTSERVICE']._serialized_end=466
# @@protoc_insertion_point(module_scope)
