# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kr/co/lguplus/engine/service/v1/stt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kr.co.lguplus.engine.model.v1 import stt_pb2 as kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)kr/co/lguplus/engine/service/v1/stt.proto\x12\x1fkr.co.lguplus.engine.service.v1\x1a\'kr/co/lguplus/engine/model/v1/stt.proto2w\n\nSttService\x12i\n\tGetStream\x12,.kr.co.lguplus.engine.model.v1.StreamRequest\x1a*.kr.co.lguplus.engine.model.v1.StreamReply(\x01\x30\x01\x42\x02P\x01\x62\x06proto3')



_STTSERVICE = DESCRIPTOR.services_by_name['SttService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _STTSERVICE._serialized_start=119
  _STTSERVICE._serialized_end=238
# @@protoc_insertion_point(module_scope)
