# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.kr.co.lguplus.engine.model.v1 import stt_pb2 as kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2


class SttServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStream = channel.stream_stream(
                '/kr.co.lguplus.engine.service.v1.SttService/GetStream',
                request_serializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamRequest.SerializeToString,
                response_deserializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamReply.FromString,
                )


class SttServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SttServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamRequest.FromString,
                    response_serializer=kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kr.co.lguplus.engine.service.v1.SttService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SttService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/kr.co.lguplus.engine.service.v1.SttService/GetStream',
            kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamRequest.SerializeToString,
            kr_dot_co_dot_lguplus_dot_engine_dot_model_dot_v1_dot_stt__pb2.StreamReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
