# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kr/co/lguplus/engine/model/v1/stt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'kr/co/lguplus/engine/model/v1/stt.proto\x12\x1dkr.co.lguplus.engine.model.v1\"G\n\rStreamRequest\x12\x14\n\x0cquery_header\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\"b\n\x0bStreamReply\x12\x14\n\x0cquery_header\x18\x01 \x01(\x05\x12\x12\n\nepd_result\x18\x02 \x01(\x05\x12\x12\n\nstt_result\x18\x03 \x01(\t\x12\x15\n\rconnect_reply\x18\x04 \x01(\x05\x42\x02P\x01\x62\x06proto3')



_STREAMREQUEST = DESCRIPTOR.message_types_by_name['StreamRequest']
_STREAMREPLY = DESCRIPTOR.message_types_by_name['StreamReply']
StreamRequest = _reflection.GeneratedProtocolMessageType('StreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREQUEST,
  '__module__' : 'kr.co.lguplus.engine.model.v1.stt_pb2'
  # @@protoc_insertion_point(class_scope:kr.co.lguplus.engine.model.v1.StreamRequest)
  })
_sym_db.RegisterMessage(StreamRequest)

StreamReply = _reflection.GeneratedProtocolMessageType('StreamReply', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREPLY,
  '__module__' : 'kr.co.lguplus.engine.model.v1.stt_pb2'
  # @@protoc_insertion_point(class_scope:kr.co.lguplus.engine.model.v1.StreamReply)
  })
_sym_db.RegisterMessage(StreamReply)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _STREAMREQUEST._serialized_start=74
  _STREAMREQUEST._serialized_end=145
  _STREAMREPLY._serialized_start=147
  _STREAMREPLY._serialized_end=245
# @@protoc_insertion_point(module_scope)
