# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kr/co/lguplus/engine/model/v1/stt.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'kr/co/lguplus/engine/model/v1/stt.proto\x12\x1dkr.co.lguplus.engine.model.v1\"G\n\rStreamRequest\x12\x14\n\x0cquery_header\x18\x01 \x01(\x05\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\"b\n\x0bStreamReply\x12\x14\n\x0cquery_header\x18\x01 \x01(\x05\x12\x12\n\nepd_result\x18\x02 \x01(\x05\x12\x12\n\nstt_result\x18\x03 \x01(\t\x12\x15\n\rconnect_reply\x18\x04 \x01(\x05\"4\n\x0fLMUpdateRequest\x12\x0f\n\x07lm_name\x18\x01 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x02 \x01(\t\" \n\rLMUpdateReply\x12\x0f\n\x07success\x18\x01 \x01(\x05\"$\n\x14InterLMUpdateRequest\x12\x0c\n\x04port\x18\x01 \x01(\x05\"%\n\x12InterLMUpdateReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kr.co.lguplus.engine.model.v1.stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_STREAMREQUEST']._serialized_start=74
  _globals['_STREAMREQUEST']._serialized_end=145
  _globals['_STREAMREPLY']._serialized_start=147
  _globals['_STREAMREPLY']._serialized_end=245
  _globals['_LMUPDATEREQUEST']._serialized_start=247
  _globals['_LMUPDATEREQUEST']._serialized_end=299
  _globals['_LMUPDATEREPLY']._serialized_start=301
  _globals['_LMUPDATEREPLY']._serialized_end=333
  _globals['_INTERLMUPDATEREQUEST']._serialized_start=335
  _globals['_INTERLMUPDATEREQUEST']._serialized_end=371
  _globals['_INTERLMUPDATEREPLY']._serialized_start=373
  _globals['_INTERLMUPDATEREPLY']._serialized_end=410
# @@protoc_insertion_point(module_scope)
